Add badges to readme
gh-conf/rhof pull request #50
Opened 2022-10-03 19:09 UTC by pwnb0y

#49

2022-10-03 19:52 UTC, arshadkazmi42 requested changes
Thank you for working on this.

I have added two minor changes. I forgot to mention this in the issue, sorry about that.

Can you make these changes? We can get this merged once the changes are done

2022-10-03 19:52 UTC, arshadkazmi42 commented on README.md
> +[![Build](https://github.com/pwnb0y/rhof/actions/workflows/nodejs.yml/badge.svg)](https://github.com/pwnb0y/rhof/actions/workflows/nodejs.yml)
`pwnb0y` => `gh-conf`

seems there is some issue with the `npm-badger` tool. It used your username.

Can you update this? Find and replace in the whole file

2022-10-03 19:52 UTC, arshadkazmi42 commented on README.md
>  <!-- Add Badges here -->
Can we also remove these from line 3 to 9 since we are using badges added by npm-badger now

2022-10-04 09:13 UTC, arshadkazmi42 commented on README.md
> +[![Build](https://github.com/pwnb0y/rhof/actions/workflows/nodejs.yml/badge.svg)](https://github.com/pwnb0y/rhof/actions/workflows/nodejs.yml)
@pwnb0y I think my comments were not clear.

I meant in these lines https://github.com/gh-conf/rhof/pull/50/commits/916dc6db699a2321cc12141443e5aad7d223208f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R3-R9

replace `pwnb0y` => `gh-conf`

2022-10-04 09:14 UTC, arshadkazmi42 commented on README.md
>  <!-- Add Badges here -->
Remove these lines https://github.com/gh-conf/rhof/pull/50/commits/916dc6db699a2321cc12141443e5aad7d223208f#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R12-R18

2022-10-04 09:14 UTC, arshadkazmi42 commented
@pwnb0y I think my comments were not very clear. I updated comments we will need changes according to that. Seems latest commit reverted all the changes and now there is no changes are present in the PR

2022-10-04 20:18 UTC, pwnb0y commented
Hey @arshadkazmi42 can you review it again

2022-10-04 20:30 UTC, arshadkazmi42 requested changes
You have missed one

2022-10-04 20:30 UTC, arshadkazmi42 commented on README.md
>  <!-- Add Badges here -->
@pwnb0y this is still pending. We can remove line 12 - 18 in README.md

2022-10-05 07:14 UTC, pwnb0y commented
Ok

2022-10-05 08:45 UTC, arshadkazmi42 approved these changes
LGTM 🎉

2022-10-05 08:45 UTC, merged